config/routes.rb
Rails.application.routes.draw do
  resources :messages
  post 'messages/reply'

  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :user, :text, presence: true
  validates :number, presence: true, length: { is: 12}
  phony_normalize :number, default_country_code: 'US'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @messages = Message.all
    puts Rails.application.secrets

  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  # Create a new message and send an SMS text.
  def create
    @message = Message.new(message_params)
    if @message.save
      @message.action = 'SEND'
      @message.save

      # Send SMS text
      boot_twilio
      sms = @client.messages.create(
        body: @message.text,
        from: Rails.application.secrets.twilio_number,
        to: @message.number,
      )
      redirect_to @message, alert: "SMS Text sent."
    else
      render 'new'
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    redirect_to messages_path
  end

  # Webhook for Twilio to forward replies.
  # Store any replies in the db and send back a a simple reply.
  def reply
    message_body = params["Body"]
    from_number = params["From"]
    @recent_msg = Message.where(number: from_number).last # Get the name of this user if possible

    # Some random schmoe not in our db is trying to text me.
    if @recent_msg.blank?
      head 200, "content_type" => 'text/html'
      return
    end

    user = @recent_msg.user

    # Store reply in db and send back a simple text.
    @message = Message.new(user: user, number: from_number, text: message_body, action: 'REPLY')
    if @message.save
      boot_twilio
      sms = @client.messages.create(
        from: Rails.application.secrets.twilio_number,
        to: from_number,
        body: "Hello from the other side! Your number is #{from_number}."
      )
    end
    head 200, "content_type" => 'text/html'
  end

  private
    def message_params
      params.require(:message).permit(:user, :number, :text)
    end

    # Twilio setup client.
    def boot_twilio
      account_sid = Rails.application.secrets.twilio_sid
      auth_token = Rails.application.secrets.twilio_token
      @client = Twilio::REST::Client.new(account_sid, auth_token)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TextApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with scope: :message, url: messages_path, local: true do |form| %>

  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@message.errors.count, "error") %> prohibited
        this message from being saved:
      </h2>
      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :user, required: true, autofocus: true, placeholder: "Name" %>
  </div><br>

  <div class="field">
    <%= form.text_field :number, required: true, autofocus: true, placeholder: "Telephone Number" %>
  </div><br>

  <div class="field">
    <%= form.text_area :text, required: true, autofocus: true, placeholder: "SMS Text" %>
  </div>

  <div class="actions">
    <%= form.submit "Send SMS Text" %>
  </div>

<% end %>

app/views/messages/index.html.erb
<h1>Showing All Messages</h1>

<%= link_to 'New Message', new_message_path %> <br>

<table>
  <tr>
    <th>User</th>
    <th>Number</th>
    <th>Text</th>
    <th>Time</th>
    <th>Action</th>
    <th></th>
    <th></th>
  </tr>

  <% @messages.each do |message| %>
    <tr>
      <td><%= message.user %></td>
      <td><%= message.number %></td>
      <td><%= message.text %></td>
      <td><%= message.created_at %></td>
      <td><%= message.action %></td>
      <td><%= link_to 'Show', message_path(message) %></td>
      <td><%= link_to 'Delete', message_path(message),
          method: :delete,
          data: { confirm: 'Are you sure?' }%></td>
    </tr>
  <% end %>

</table>

app/views/messages/new.html.erb
<h1>Send SMS Text</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p>
  <strong>User:</strong>
  <%= @message.user %>
</p>

<p>
  <strong>Number:</strong>
  <%= @message.number %>
</p>

<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>

<p>
  <strong>Time:</strong>
  <%= @message.created_at %>
</p>

<p>
  <strong>Action:</strong>
  <%= @message.action %>
</p>

<%= link_to 'Back', messages_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Messages', controller: 'messages' %>